//
// Created by bfa-oren on 19-7-5.
//

#ifndef SOFT_BODY_CONTROL_CONFIGHEADER_H
#define SOFT_BODY_CONTROL_CONFIGHEADER_H

//#define WHOLE_ACTIVE_SETTING
#define SELECTED_ACTIVE_SETTING

//#define STATIC_SOLVER

#endif //SOFT_BODY_CONTROL_CONFIGHEADER_H
